runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html
- url: /api/channels/.*
  script: backend.api.app
